export const data = [
  {
    region: 'Región de Arica y Parinacota',
    cities: [
      { city: 'Arica' },
      { city: 'Camarones' },
      { city: 'General Lagos' },
      { city: 'Putre' },
    ],
  },
  {
    region: 'Región de Tarapacá',
    cities: [
      { city: 'Alto Hospicio' },
      { city: 'Camiña' },
      { city: 'Colchane' },
      { city: 'Huara' },
      { city: 'Iquique' },
      { city: 'Pica' },
      { city: 'Pozo Almonte' },
    ],
  },
  {
    region: 'Región de Antofagasta',
    cities: [
      { city: 'Antofagasta' },
      { city: 'Calama' },
      { city: 'María Elena' },
      { city: 'Mejillones' },
      { city: 'Ollagüe' },
      { city: 'San Pedro de Atacama' },
      { city: 'Sierra Gorda' },
      { city: 'Taltal' },
      { city: 'Tocopilla' },
    ],
  },
  {
    region: 'Región de Atacama',
    cities: [
      { city: 'Alto del Carmen' },
      { city: 'Caldera' },
      { city: 'Chañaral' },
      { city: 'Copiapó' },
      { city: 'Diego de Almagro' },
      { city: 'Freirina' },
      { city: 'Huasco' },
      { city: 'Tierra Amarilla' },
      { city: 'Vallenar' },
    ],
  },
  {
    region: 'Región de Coquimbo',
    cities: [
      { city: 'Andacollo' },
      { city: 'Canela' },
      { city: 'Combarbalá' },
      { city: 'Coquimbo' },
      { city: 'Illapel' },
      { city: 'La Higuera' },
      { city: 'La Serena' },
      { city: 'Los Vilos' },
      { city: 'Monte Patria' },
      { city: 'Ovalle' },
      { city: 'Paihuano' },
      { city: 'Punitaqui' },
      { city: 'Río Hurtado' },
      { city: 'Salamanca' },
      { city: 'Vicuña' },
    ],
  },
  {
    region: 'Región de Valparaíso',
    cities: [
      { city: 'Algarrobo' },
      { city: 'Cabildo' },
      { city: 'Calera' },
      { city: 'Calle Larga' },
      { city: 'Cartagena' },
      { city: 'Casablanca' },
      { city: 'Catemu' },
      { city: 'Concón' },
      { city: 'El Quisco' },
      { city: 'El Tabo' },
      { city: 'Hijuelas' },
      { city: 'Isla de Pascua' },
      { city: 'Juan Fernández' },
      { city: 'La Cruz' },
      { city: 'La Ligua' },
      { city: 'Limache' },
      { city: 'Llaillay' },
      { city: 'Los Andes' },
      { city: 'Nogales' },
      { city: 'Olmué' },
      { city: 'Panquehue' },
      { city: 'Papudo' },
      { city: 'Petorca' },
      { city: 'Puchuncaví' },
      { city: 'Putaendo' },
      { city: 'Quillota' },
      { city: 'Quilpué' },
      { city: 'Quintero' },
      { city: 'Rinconada' },
      { city: 'San Antonio' },
      { city: 'San Esteban' },
      { city: 'San Felipe' },
      { city: 'Santa María' },
      { city: 'Santo Domingo' },
      { city: 'Valparaíso' },
      { city: 'Villa Alemana' },
      { city: 'Viña del Mar' },
      { city: 'Zapallar' },
    ],
  },
  {
    region: "Región del Libertador General Bernardo O'Higgins",
    cities: [
      { city: 'Chépica' },
      { city: 'Chimbarongo' },
      { city: 'Codegua' },
      { city: 'Coínco' },
      { city: 'Coltauco' },
      { city: 'Doñihue' },
      { city: 'Graneros' },
      { city: 'La Estrella' },
      { city: 'Las Cabras' },
      { city: 'Litueche' },
      { city: 'Lolol' },
      { city: 'Machalí' },
      { city: 'Malloa' },
      { city: 'Marchihue' },
      { city: 'Mostazal' },
      { city: 'Nancagua' },
      { city: 'Navidad' },
      { city: 'Olivar' },
      { city: 'Palmilla' },
      { city: 'Paredones' },
      { city: 'Peralillo' },
      { city: 'Peumo' },
      { city: 'Pichidegua' },
      { city: 'Pichilemu' },
      { city: 'Placilla' },
      { city: 'Pumanque' },
      { city: 'Quinta de Tilcoco' },
      { city: 'Rancagua' },
      { city: 'Rengo' },
      { city: 'Requínoa' },
      { city: 'San Fernando' },
      { city: 'Santa Cruz' },
      { city: 'San Vicente' },
    ],
  },
  {
    region: 'Región del Maule',
    cities: [
      { city: 'Cauquenes' },
      { city: 'Chanco' },
      { city: 'Colbún' },
      { city: 'Constitución' },
      { city: 'Curepto' },
      { city: 'Curicó' },
      { city: 'Empedrado' },
      { city: 'Hualañé' },
      { city: 'Licantén' },
      { city: 'Linares' },
      { city: 'Longaví' },
      { city: 'Maule' },
      { city: 'Molina' },
      { city: 'Parral' },
      { city: 'Pelarco' },
      { city: 'Pelluhue' },
      { city: 'Pencahue' },
      { city: 'Rauco' },
      { city: 'Retiro' },
      { city: 'Río Claro' },
      { city: 'Romeral' },
      { city: 'Sagrada Familia' },
      { city: 'San Clemente' },
      { city: 'San Javier' },
      { city: 'San Rafael' },
      { city: 'Talca' },
      { city: 'Teno' },
      { city: 'Vichuquén' },
      { city: 'Villa Alegre' },
      { city: 'Yerbas Buenas' },
    ],
  },
  {
    region: 'Región de Ñuble',
    cities: [
      { city: 'Bulnes' },
      { city: 'Chillán' },
      { city: 'Chillán Viejo' },
      { city: 'Cobquecura' },
      { city: 'Coelemu' },
      { city: 'Coihueco' },
      { city: 'El Carmen' },
      { city: 'Ninhue' },
      { city: 'Ñiquén' },
      { city: 'Pemuco' },
      { city: 'Pinto' },
      { city: 'Portezuelo' },
      { city: 'Quillón' },
      { city: 'Quirihue' },
      { city: 'Ránquil' },
      { city: 'San Carlos' },
      { city: 'San Fabián' },
      { city: 'San Ignacio' },
      { city: 'San Nicolás' },
      { city: 'Treguaco' },
      { city: 'Yungay' },
    ],
  },
  {
    region: 'Región del Biobío',
    cities: [
      { city: 'Alto Biobío' },
      { city: 'Antuco' },
      { city: 'Arauco' },
      { city: 'Cabrero' },
      { city: 'Cañete' },
      { city: 'Chiguayante' },
      { city: 'Concepción' },
      { city: 'Contulmo' },
      { city: 'Coronel' },
      { city: 'Curanilahue' },
      { city: 'Florida' },
      { city: 'Hualpén' },
      { city: 'Hualqui' },
      { city: 'Laja' },
      { city: 'Lebu' },
      { city: 'Los Alamos' },
      { city: 'Los Angeles' },
      { city: 'Lota' },
      { city: 'Mulchén' },
      { city: 'Nacimiento' },
      { city: 'Negrete' },
      { city: 'Penco' },
      { city: 'Quilaco' },
      { city: 'Quilleco' },
      { city: 'San Pedro de la Paz' },
      { city: 'San Rosendo' },
      { city: 'Santa Bárbara' },
      { city: 'Santa Juana' },
      { city: 'Talcahuano' },
      { city: 'Tirúa' },
      { city: 'Tomé' },
      { city: 'Tucapel' },
      { city: 'Yumbel' },
    ],
  },
  {
    region: 'Región de La Araucanía',
    cities: [
      { city: 'Angol' },
      { city: 'Carahue' },
      { city: 'Cholchol' },
      { city: 'Collipulli' },
      { city: 'Cunco' },
      { city: 'Curacautín' },
      { city: 'Curarrehue' },
      { city: 'Ercilla' },
      { city: 'Freire' },
      { city: 'Galvarino' },
      { city: 'Gorbea' },
      { city: 'Lautaro' },
      { city: 'Loncoche' },
      { city: 'Lonquimay' },
      { city: 'Los Sauces' },
      { city: 'Lumaco' },
      { city: 'Melipeuco' },
      { city: 'Nueva Imperial' },
      { city: 'Padre Las Casas' },
      { city: 'Perquenco' },
      { city: 'Pitrufquén' },
      { city: 'Pucón' },
      { city: 'Purén' },
      { city: 'Renaico' },
      { city: 'Saavedra' },
      { city: 'Temuco' },
      { city: 'Teodoro Schmidt' },
      { city: 'Toltén' },
      { city: 'Traiguén' },
      { city: 'Victoria' },
      { city: 'Vilcún' },
      { city: 'Villarrica' },
    ],
  },
  {
    region: 'Región de Los Ríos',
    cities: [
      { city: 'Corral' },
      { city: 'Futrono' },
      { city: 'Lago Ranco' },
      { city: 'Lanco' },
      { city: 'La Unión' },
      { city: 'Los Lagos' },
      { city: 'Máfil' },
      { city: 'Mariquina' },
      { city: 'Paillaco' },
      { city: 'Panguipulli' },
      { city: 'Río Bueno' },
      { city: 'Valdivia' },
    ],
  },
  {
    region: 'Región de Los Lagos',
    cities: [
      { city: 'Ancud' },
      { city: 'Calbuco' },
      { city: 'Castro' },
      { city: 'Chaitén' },
      { city: 'Chonchi' },
      { city: 'Cochamó' },
      { city: 'Curaco de Vélez' },
      { city: 'Dalcahue' },
      { city: 'Fresia' },
      { city: 'Frutillar' },
      { city: 'Futaleufú' },
      { city: 'Hualaihué' },
      { city: 'Llanquihue' },
      { city: 'Los Muermos' },
      { city: 'Maullín' },
      { city: 'Osorno' },
      { city: 'Palena' },
      { city: 'Puerto Montt' },
      { city: 'Puerto Octay' },
      { city: 'Puerto Varas' },
      { city: 'Puqueldón' },
      { city: 'Purranque' },
      { city: 'Puyehue' },
      { city: 'Queilén' },
      { city: 'Quellón' },
      { city: 'Quemchi' },
      { city: 'Quinchao' },
      { city: 'Río Negro' },
      { city: 'San Juan de la Costa' },
      { city: 'San Pablo' },
    ],
  },
  {
    region: 'Región de Aysén del G. Carlos Ibáñez del Campo',
    cities: [
      { city: 'Aysén' },
      { city: 'Chile Chico' },
      { city: 'Cisnes' },
      { city: 'Cochrane' },
      { city: 'Coyhaique' },
      { city: 'Guaitecas' },
      { city: 'Lago Verde' },
      { city: "O'Higgins" },
      { city: 'Río Ibáñez' },
      { city: 'Tortel' },
    ],
  },
  {
    region: 'Región de Magallanes y de la Antártica Chilena',
    cities: [
      { city: 'Antártica' },
      { city: 'Cabo de Hornos' },
      { city: 'Laguna Blanca' },
      { city: 'Natales' },
      { city: 'Porvenir' },
      { city: 'Primavera' },
      { city: 'Punta Arenas' },
      { city: 'Río Verde' },
      { city: 'San Gregorio' },
      { city: 'Timaukel' },
      { city: 'Torres del Paine' },
    ],
  },
  {
    region: 'Región Metropolitana de Santiago',
    cities: [
      { city: 'Alhué' },
      { city: 'Buin' },
      { city: 'Calera de Tango' },
      { city: 'Cerrillos' },
      { city: 'Cerro Navia' },
      { city: 'Colina' },
      { city: 'Conchalí' },
      { city: 'Curacaví' },
      { city: 'El Bosque' },
      { city: 'El Monte' },
      { city: 'Estación Central' },
      { city: 'Huechuraba' },
      { city: 'Independencia' },
      { city: 'Isla de Maipo' },
      { city: 'La Cisterna' },
      { city: 'La Florida' },
      { city: 'La Granja' },
      { city: 'Lampa' },
      { city: 'La Pintana' },
      { city: 'La Reina' },
      { city: 'Las Condes' },
      { city: 'Lo Barnechea' },
      { city: 'Lo Espejo' },
      { city: 'Lo Prado' },
      { city: 'Macul' },
      { city: 'Maipú' },
      { city: 'María Pinto' },
      { city: 'Melipilla' },
      { city: 'Ñuñoa' },
      { city: 'Padre Hurtado' },
      { city: 'Paine' },
      { city: 'Pedro Aguirre Cerda' },
      { city: 'Peñaflor' },
      { city: 'Peñalolén' },
      { city: 'Pirque' },
      { city: 'Providencia' },
      { city: 'Pudahuel' },
      { city: 'Puente Alto' },
      { city: 'Quilicura' },
      { city: 'Quinta Normal' },
      { city: 'Recoleta' },
      { city: 'Renca' },
      { city: 'San Bernardo' },
      { city: 'San Joaquín' },
      { city: 'San José de Maipo' },
      { city: 'San Miguel' },
      { city: 'San Pedro' },
      { city: 'San Ramón' },
      { city: 'Santiago' },
      { city: 'Talagante' },
      { city: 'Tiltil' },
      { city: 'Vitacura' },
    ],
  },
]
